from django.urls import path

from . import views
from .views import update_worker_status

urlpatterns = [
    path(
        "signup/",
        views.signup,
        name="signup",
    ),
    path(
        "verify-otp/",
        views.verify_otp,
        name="verify-otp",
    ),
    path(
        "resend-otp/",
        views.resend_otp,
        name="resend-otp",
    ),
    path(
        "worker/skills/",
        views.get_skills,
        name="worker-skills",
    ),
    path(
        "worker/dashboard/",
        views.worker_dashboard,
        name="worker-dashboard",
    ),
    path(
        "worker/select-skills/",
        views.select_skills,
        name="worker-select-skills",
    ),
    path(
        "worker/status/",
        update_worker_status,
        name="worker-status",
    ),
    path(
        "worker/profile/",
        views.worker_profile,
        name="worker-profile",
    ),
    path(
        "worker/profile/photo/",
        views.upload_profile_photo,
        name="worker-profile-photo",
    ),
    path(
        "worker/identity/",
        views.upload_identity_documents,
        name="worker-identity",
    ),
    path(
        "worker/update-skills/",
        views.update_skills,
        name="worker-update-skills",
    ),
    path(
        "worker/incoming-requests/",
        views.incoming_requests,
    ),
    path(
        "worker/request/<int:offer_id>/",
        views.request_detail,
    ),
    path(
        "worker/request/<int:offer_id>/accept/",
        views.accept_request,
    ),
    path(
        "worker/request/<int:offer_id>/reject/",
        views.reject_request,
        name="reject-request",
    ),
    path(
        "worker/current-job/",
        views.current_job,
        name="current-job",
    ),
    path(
        "worker/location/",
        views.update_location,
        name="worker-location",
    ),
    path(
        "worker/request/<int:offer_id>/start/",
        views.start_job,
        name="start-job",
    ),
    path(
        "worker/request/<int:offer_id>/complete/",
        views.complete_job,
        name="complete-job",
    ),
    path(
        "customer/profile/",
        views.customer_profile,
        name="customer-profile",
    ),

    path(
        "customer/profile/update/",
        views.update_customer_profile,
        name="update-customer-profile",
    ),
        path(
        "customer/profile-photo/",
        views.update_customer_profile_photo,
        name="customer-profile-photo",
    ),
    path("login/", views.user_login, name="user-login"),
    path("refresh/", views.user_refresh, name="user-refresh"),
    path("logout/", views.user_logout, name="user-logout"),
]
