# Generated by Django 6.0.6 on 2026-07-17 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_workerprofile_current_latitude_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('rxpired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('offered_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='services.booking')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_offers', to='accounts.workerprofile')),
            ],
        ),
    ]
