# Generated by Django 6.0.6 on 2026-07-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_bookingoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='job_progress',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('working', 'Working'), ('completed', 'Completed')], default='accepted', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingoffer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
