# Generated by Django 6.0.6 on 2026-07-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_booking_job_progress_alter_bookingoffer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='job_progress',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('assigned', 'Assigned')], default='active', max_length=20),
        ),
    ]
