# Generated by Django 6.0.6 on 2026-07-18 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_booking_job_progress_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='job_progress',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('working', 'Working'), ('completed', 'Completed')], default='accepted', max_length=20),
        ),
    ]
