# Generated by Django 6.0.6 on 2026-07-31 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_booking_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='review_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
