# Generated by Django 6.0.6 on 2026-08-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_booking_review_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_km', models.DecimalField(decimal_places=2, default=100.0, max_digits=8)),
                ('minimum_visit_charge', models.DecimalField(decimal_places=2, default=100.0, max_digits=8)),
                ('maximum_service_radius', models.DecimalField(decimal_places=2, default=5.0, help_text='Maximum distance (KM) to search nearby workers.', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
