# Generated by Django 6.0.6 on 2026-08-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_pricingconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingoffer',
            name='visit_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
