# Generated by Django 6.0.6 on 2026-08-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_bookingoffer_visit_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='job_progress',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='price',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('scheduled', 'Scheduled'), ('assigned', 'Assigned'), ('working', 'Working'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
