# Generated by Django 6.0.6 on 2026-07-03 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pendingregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='citizenship_back',
            field=models.ImageField(blank=True, null=True, upload_to='citizenship/back/'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='citizenship_front',
            field=models.ImageField(blank=True, null=True, upload_to='citizenship/front/'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='permanent_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
