# Generated by Django 6.0.6 on 2026-07-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_skill_workerprofile_has_selected_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
