# Generated by Django 6.0.6 on 2026-07-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_skill_workerprofile_has_selected_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='skills/icons/'),
        ),
    ]
