# Generated by Django 6.0.6 on 2026-07-14 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_skill_icon'),
        ('accounts', '0007_skill_display_order'),
    ]

    operations = [
    ]
