# Generated by Django 6.0.6 on 2026-07-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_skill_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='about_me',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='service_areas',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
