# Generated by Django 6.0.6 on 2026-07-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_workerprofile_about_me_workerprofile_service_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='experience_document',
            field=models.ImageField(blank=True, null=True, upload_to='experience_documents/'),
        ),
    ]
