# Generated by Django 6.0.6 on 2026-07-15 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merge_0007_alter_skill_icon_0007_skill_display_order'),
        ('accounts', '0009_workerprofile_experience_document'),
    ]

    operations = [
    ]
