# Generated by Django 6.0.6 on 2026-07-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_workerprofile_current_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
