# Generated by Django 6.0.6 on 2026-08-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_skill_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('worker', 'Worker'), ('admin', 'Admin')], max_length=20),
        ),
    ]
