# Generated by Django 6.0.6 on 2026-08-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprofile',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
